export const mockSubroutes = [
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'ltSurge',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'erika',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'silphCoRival',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'koga',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'sabrina',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'blaine',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'route22Rival',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'lorelei',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'agatha',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'lance',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_NO_TMS',
		trainer: 'champion',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'ltSurge',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'erika',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'silphCoRival',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'koga',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'sabrina',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'blaine',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'route22Rival',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'lorelei',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'agatha',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'lance',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		trainer: 'champion',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'ltSurge',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'erika',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'silphCoRival',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'koga',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'sabrina',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'blaine',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'route22Rival',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'lorelei',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'agatha',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'lance',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		trainer: 'champion',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'ltSurge',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'erika',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'silphCoRival',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'koga',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'sabrina',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'blaine',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'route22Rival',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'lorelei',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'agatha',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'lance',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		trainer: 'champion',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'ltSurge',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'erika',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'silphCoRival',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'koga',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'sabrina',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'blaine',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'route22Rival',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'lorelei',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'agatha',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'lance',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'champion',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'ltSurge',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'erika',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'silphCoRival',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'koga',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'sabrina',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'blaine',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'route22Rival',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'lorelei',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'agatha',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'lance',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		trainer: 'champion',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'ltSurge',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'erika',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'silphCoRival',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'koga',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'sabrina',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'blaine',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'route22Rival',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'lorelei',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'agatha',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'lance',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		trainer: 'champion',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'ltSurge',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'erika',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'silphCoRival',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'koga',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'sabrina',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'blaine',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'route22Rival',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'lorelei',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'agatha',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'lance',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		trainer: 'champion',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'bulbasaur',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'brock',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'misty',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'ltSurge',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'erika',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'erika',
		score: 2.5,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'silphCoRival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'koga',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'sabrina',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'route22Rival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'lorelei',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'agatha',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'lance',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		trainer: 'champion',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'brock',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'misty',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'ltSurge',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'erika',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'erika',
		score: 4.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'silphCoRival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'koga',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'sabrina',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'route22Rival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'lorelei',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'agatha',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'lance',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		trainer: 'champion',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'brock',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'misty',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'ltSurge',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'erika',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'erika',
		score: 4.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'silphCoRival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'koga',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'sabrina',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'route22Rival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'lorelei',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'agatha',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'lance',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		trainer: 'champion',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'brock',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'misty',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'ltSurge',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'erika',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'erika',
		score: 2.5,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'silphCoRival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'koga',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'sabrina',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'route22Rival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'lorelei',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'agatha',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'lance',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		trainer: 'champion',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'brock',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'misty',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'ltSurge',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'erika',
		score: 0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'erika',
		score: 4.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'silphCoRival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'koga',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'sabrina',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'route22Rival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'lorelei',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'agatha',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'lance',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		trainer: 'champion',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'brock',
		score: 2.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'misty',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'ltSurge',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'erika',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'erika',
		score: 4.0,
		healingItemsCount: 1,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'silphCoRival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'koga',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'sabrina',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'route22Rival',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'lorelei',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'bruno',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'agatha',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'lance',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		trainer: 'champion',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'charmander',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'ltSurge',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'erika',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'silphCoRival',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'koga',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'sabrina',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'route22Rival',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'lorelei',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'agatha',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'lance',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		trainer: 'champion',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'brock',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'misty',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'ltSurge',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'erika',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'silphCoRival',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'koga',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'sabrina',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'blaine',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'route22Rival',
		score: 4.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'lorelei',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'agatha',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'lance',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		trainer: 'champion',
		score: 4.5,
		healingItemsCount: 0,
		pokemonId: 'squirtle',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'brock',
		score: 0.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: true,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'misty',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'ltSurge',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'erika',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'silphCoRival',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'koga',
		score: 2.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'sabrina',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'blaine',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'route22Rival',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'lorelei',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'agatha',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'lance',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		trainer: 'champion',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'brock',
		score: 0.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'brock',
		score: 3.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: true,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'misty',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'ltSurge',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'erika',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'silphCoRival',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'koga',
		score: 3.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'sabrina',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'blaine',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'giovanni',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'route22Rival',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'lorelei',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'bruno',
		score: 5.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'agatha',
		score: 1.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'lance',
		score: 1.0,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		trainer: 'champion',
		score: 0.5,
		healingItemsCount: 0,
		pokemonId: 'caterpie',
		excluded: false,
	},
];
