export const mockRoutes = [
	{
		routeId: 'BULBASAUR_NO_TMS',
		pokemonId: 'bulbasaur',
		tmsModifier: 1.0,
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_BODY_SLAM',
		pokemonId: 'bulbasaur',
		tmsModifier: 0.81,
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_TAKE_DOWN',
		pokemonId: 'bulbasaur',
		tmsModifier: 0.9,
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_DOUBLE_EDGE',
		pokemonId: 'bulbasaur',
		tmsModifier: 0.855,
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		pokemonId: 'bulbasaur',
		tmsModifier: 0.9,
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_HYPER_BEAM',
		pokemonId: 'bulbasaur',
		tmsModifier: 1.0,
		excluded: true,
	},
	{
		routeId: 'BULBASAUR_WITH_DOUBLE_EDGE',
		pokemonId: 'bulbasaur',
		tmsModifier: 0.95,
		excluded: false,
	},
	{
		routeId: 'BULBASAUR_WITH_BODY_SLAM',
		pokemonId: 'bulbasaur',
		tmsModifier: 0.9,
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_NO_TMS',
		pokemonId: 'charmander',
		tmsModifier: 1.0,
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_DIG',
		pokemonId: 'charmander',
		tmsModifier: 0.81,
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE',
		pokemonId: 'charmander',
		tmsModifier: 0.9,
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_DIG',
		pokemonId: 'charmander',
		tmsModifier: 0.9,
		excluded: false,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_AND_HYPER_BEAM',
		pokemonId: 'charmander',
		tmsModifier: 0.9,
		excluded: true,
	},
	{
		routeId: 'CHARMANDER_WITH_SWORDS_DANCE_HYPER_BEAM_AND_DIG',
		pokemonId: 'charmander',
		tmsModifier: 0.81,
		excluded: true,
	},
	{
		routeId: 'SQUIRTLE_NO_TMS',
		pokemonId: 'squirtle',
		tmsModifier: 1.0,
		excluded: false,
	},
	{
		routeId: 'SQUIRTLE_WITH_ICE_BEAM',
		pokemonId: 'squirtle',
		tmsModifier: 0.9,
		excluded: false,
	},
	{
		routeId: 'CATERPIE_NO_TMS',
		pokemonId: 'caterpie',
		tmsModifier: 1.0,
		excluded: false,
	},
	{
		routeId: 'CATERPIE_WITH_PSYCHIC',
		pokemonId: 'caterpie',
		tmsModifier: 0.9,
		excluded: false,
	},
];
